import { useCallback, useEffect, useState, type ReactNode } from 'react';
import { Link, useNavigate, useParams } from 'react-router-dom';
import { ArrowLeft, CheckCircle2, FileText, Truck } from 'lucide-react';
import type { Json } from '@/types/database.types';
import { listarDisputasVendedorAdmin, listarEncomendasVendedorAdmin, listarHistoricoDocumentalVendedorAdmin, listarProdutosVendedorAdmin, listarServicosVendedorAdmin, obterVendedorAdmin, type DetalheVendedorAdmin, type EventoDocumentoVendedorAdmin, type PaginaAdmin, type ProdutoVendedorAdmin } from '@/services/adminVendedor360';
import { BlocoAdmin, CampoAdmin, EtiquetaEstado, formatarData, formatarKz, rotuloEstado } from './admin360Util';

type Aba = 'visao' | 'produtos' | 'servicos' | 'encomendas' | 'financeiro' | 'disputas' | 'atividade' | 'historico';
const abas: Array<{ valor: Aba; texto: string }> = [{ valor:'visao',texto:'Visão geral' },{ valor:'produtos',texto:'Produtos' },{ valor:'servicos',texto:'Serviços' },{ valor:'encomendas',texto:'Encomendas' },{ valor:'financeiro',texto:'Financeiro' },{ valor:'disputas',texto:'Disputas' },{ valor:'atividade',texto:'Atividade' }];
const LIMITE = 20;
const rotulosComerciais: Record<string, string> = { descricao:'Descrição', horario_atendimento:'Horário de atendimento', ano_inicio:'Ano de início', data_inicio_atividade:'Início de atividade', entrega_disponivel:'Entrega disponível', entrega_outras_provincias:'Entrega noutras províncias', tipo_producao:'Tipo de produção', area_cultivada:'Área cultivada', principais_culturas:'Principais culturas', producao_mensal:'Produção mensal', tipos_produtos:'Tipos de produtos', compra_produtores:'Compra a produtores', volume_minimo:'Volume mínimo', venda_grosso:'Venda a grosso', venda_retalho:'Venda a retalho', venda_presencial:'Venda presencial', tipo_loja:'Tipo de loja' };

function valorComercial(valor: Json): string { if (typeof valor === 'boolean') return valor ? 'Sim' : 'Não'; if (typeof valor === 'string' || typeof valor === 'number') return String(valor); return Array.isArray(valor) ? valor.map(valorComercial).filter(Boolean).join(', ') : ''; }
function precoConfigurado(valor: number | null): string { return valor === null ? '—' : `${new Intl.NumberFormat('pt-AO', { maximumFractionDigits: 2 }).format(valor)} Kz`; }
function Paginacao({ pagina, aoMudar }: { pagina: PaginaAdmin<unknown>; aoMudar: (offset: number) => void }) { const inicio = pagina.paginacao.totalResultados === 0 ? 0 : pagina.paginacao.offset + 1; const fim = Math.min(pagina.paginacao.offset + pagina.paginacao.limite, pagina.paginacao.totalResultados); return <div className="mt-4 flex flex-wrap items-center justify-between gap-3 border-t pt-3 text-xs text-muted-foreground"><span>{inicio}-{fim} de {pagina.paginacao.totalResultados}</span><div className="flex gap-2"><button disabled={pagina.paginacao.offset === 0} onClick={() => aoMudar(Math.max(0,pagina.paginacao.offset-pagina.paginacao.limite))} className="rounded border px-3 py-1.5 disabled:opacity-40">Anterior</button><button disabled={pagina.paginacao.offset + pagina.paginacao.limite >= pagina.paginacao.totalResultados} onClick={() => aoMudar(pagina.paginacao.offset+pagina.paginacao.limite)} className="rounded border px-3 py-1.5 disabled:opacity-40">Próxima</button></div></div>; }

export default function AdminVendedorDetalhe() {
  const { id } = useParams(); const navegar = useNavigate(); const [detalhe,setDetalhe] = useState<DetalheVendedorAdmin | null>(null); const [aba,setAba] = useState<Aba>('visao'); const [aCarregar,setACarregar] = useState(true); const [erro,setErro] = useState(false); const [produtos,setProdutos] = useState<PaginaAdmin<ProdutoVendedorAdmin> | null>(null); const [servicos,setServicos] = useState<Awaited<ReturnType<typeof listarServicosVendedorAdmin>> | null>(null); const [encomendas,setEncomendas] = useState<Awaited<ReturnType<typeof listarEncomendasVendedorAdmin>> | null>(null); const [disputas,setDisputas] = useState<Awaited<ReturnType<typeof listarDisputasVendedorAdmin>> | null>(null); const [historico,setHistorico] = useState<PaginaAdmin<EventoDocumentoVendedorAdmin> | null>(null); const [carregandoAba,setCarregandoAba] = useState(false); const [erroAba,setErroAba] = useState<string | null>(null);
  const carregar = useCallback(async () => { if (!id) { setErro(true); setACarregar(false); return; } try { setErro(false); setDetalhe(await obterVendedorAdmin(id)); } catch { setErro(true); } finally { setACarregar(false); } },[id]);
  useEffect(() => { void carregar(); },[carregar]);
  const carregarAba = useCallback(async (destino: Aba, offset = 0) => { if (!id || destino === 'visao' || destino === 'financeiro' || destino === 'atividade') return; setCarregandoAba(true); setErroAba(null); try { if (destino === 'produtos') setProdutos(await listarProdutosVendedorAdmin(id,LIMITE,offset)); if (destino === 'servicos') setServicos(await listarServicosVendedorAdmin(id,LIMITE,offset)); if (destino === 'encomendas') setEncomendas(await listarEncomendasVendedorAdmin(id,LIMITE,offset)); if (destino === 'disputas') setDisputas(await listarDisputasVendedorAdmin(id,LIMITE,offset)); if (destino === 'historico') setHistorico(await listarHistoricoDocumentalVendedorAdmin(id,LIMITE,offset)); } catch { setErroAba('Não foi possível carregar esta secção. Tente novamente.'); } finally { setCarregandoAba(false); } },[id]);
  const trocarAba = (destino: Aba) => { setAba(destino); void carregarAba(destino); };
  if (aCarregar) return <p className="painel-dashboard-form text-sm text-muted-foreground">A carregar vendedor…</p>;
  if (erro || !detalhe) return <div className="painel-dashboard-form border-destructive/30"><p className="font-semibold text-destructive">Vendedor não encontrado ou indisponível.</p><button onClick={() => void carregar()} className="mt-3 rounded-md border border-destructive px-3 py-2 text-xs font-semibold text-destructive">Tentar novamente</button></div>;
  const { vendedor, resumo, financeiro, metricas } = detalhe;
  return <div className="space-y-5"><button onClick={() => navegar('/dashboard/vendedores')} className="inline-flex items-center gap-1 text-sm text-muted-foreground hover:text-primary"><ArrowLeft className="size-4" />Voltar aos vendedores</button>
    <header className="painel-dashboard-cabecalho flex flex-col gap-4 sm:flex-row sm:items-center"><Avatar nome={vendedor.nomeComercial} foto={vendedor.fotoUrl} /><div className="relative z-10 min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><h1 className="font-titulo text-2xl font-bold text-primary-foreground">{vendedor.nomeComercial}</h1><EtiquetaEstado estado={vendedor.statusAprovacao} /><EtiquetaEstado estado={vendedor.contaAtiva ? 'conta ativa' : 'conta inativa'} />{vendedor.verificado && <span className="rounded-full bg-white/15 px-2 py-1 text-xs font-semibold text-primary-foreground">Verificado</span>}</div><p className="mt-2 text-sm text-primary-foreground/85">{vendedor.nomeResponsavel || 'Responsável não indicado'} · {rotuloEstado(vendedor.tipoVendedor)}</p><p className="mt-1 text-sm text-primary-foreground/80">{[vendedor.bairro,vendedor.municipio,vendedor.provincia].filter(Boolean).join(', ') || 'Localização não indicada'} · Plano {vendedor.plano || 'não indicado'}</p><p className="mt-3 flex items-center gap-2 text-sm font-semibold text-primary-foreground"><CheckCircle2 className="size-4" />Pode receber encomendas: {vendedor.podeReceberEncomendas ? 'Sim' : 'Não'}</p>{!vendedor.podeReceberEncomendas && vendedor.motivoInelegibilidade && <p className="mt-1 text-sm text-amber-100">{vendedor.motivoInelegibilidade}</p>}</div></header>
    {vendedor.documentosLegadosPresentes && <p className="rounded-lg border border-amber-200 bg-amber-50 p-3 text-sm text-amber-900">Este vendedor possui referências documentais do sistema legado.</p>}
    <nav className="flex gap-2 overflow-x-auto border-b pb-2" aria-label="Secções do vendedor">{abas.map(item => <button key={item.valor} onClick={() => trocarAba(item.valor)} className={`shrink-0 rounded-md px-3 py-2 text-sm font-semibold ${aba===item.valor?'bg-primary text-primary-foreground':'text-muted-foreground hover:bg-muted'}`}>{item.texto}</button>)}</nav>
    {aba === 'visao' && <Visao detalhe={detalhe} aoHistorico={() => trocarAba('historico')} />}
    {aba === 'produtos' && <Colecao estado={produtos} carregando={carregandoAba} erro={erroAba} vazio="Sem produtos." renderizar={itens => <div className="grid gap-3 sm:grid-cols-2">{itens.map(p => <article key={p.produtoId} className="rounded-lg border p-3 text-sm"><strong>{p.nome}</strong><p className="mt-2">Base: {precoConfigurado(p.precoBase)} · Promoção: {precoConfigurado(p.precoPromocional)} · Grosso: {precoConfigurado(p.precoGrosso)}</p><p className="mt-1 text-muted-foreground">{p.tipoVenda || 'Tipo não indicado'} · {p.publicado?'Publicado':'Não publicado'} · {p.disponivel?'Disponível':'Indisponível'} · {p.destaque?'Destaque':'Normal'}</p><p className="mt-1 text-muted-foreground">{p.visualizacoes} visualizações · {p.cliquesWhatsapp} cliques WhatsApp · {formatarData(p.criadoEm)}</p></article>)}</div>} aoPaginar={offset => void carregarAba('produtos',offset)} />}
    {aba === 'servicos' && <Colecao estado={servicos} carregando={carregandoAba} erro={erroAba} vazio="Sem serviços no domínio atual/legado." renderizar={itens => <div className="grid gap-3 sm:grid-cols-2">{itens.map(s => <article key={s.servicoId} className="rounded-lg border p-3 text-sm"><strong>{s.nome}</strong><p className="mt-2">Preço estimado: {precoConfigurado(s.precoEstimado)}</p><p className="mt-1 text-muted-foreground">{s.tipoServico || 'Tipo não indicado'} · {s.publicado?'Publicado':'Não publicado'} · {s.disponivel?'Disponível':'Indisponível'} · {s.destaque?'Destaque':'Normal'}</p><p className="mt-1 text-muted-foreground">{s.visualizacoes} visualizações · {s.cliquesWhatsapp} cliques WhatsApp · {formatarData(s.criadoEm)}</p></article>)}</div>} aoPaginar={offset => void carregarAba('servicos',offset)} />}
    {aba === 'encomendas' && <Colecao estado={encomendas} carregando={carregandoAba} erro={erroAba} vazio="Sem encomendas." renderizar={itens => <div className="space-y-2">{itens.map(e => <article key={e.encomendaId} className="rounded-lg border p-3 text-sm"><div className="flex flex-wrap justify-between gap-2"><strong>{e.codigoPublico}</strong><Link className="text-primary underline" to={`/dashboard/encomendas/${e.encomendaId}`}>Ver encomenda</Link></div><p className="mt-1">{e.clienteNome} · {formatarKz(e.totalCentimos)} · {formatarData(e.criadoEm)}</p><div className="mt-2 flex flex-wrap gap-2"><EtiquetaEstado estado={e.estado}/><EtiquetaEstado estado={e.estadoPagamento}/>{e.temDisputa && <EtiquetaEstado estado="com disputa"/>}</div></article>)}</div>} aoPaginar={offset => void carregarAba('encomendas',offset)} />}
    {aba === 'financeiro' && <Financeiro financeiro={financeiro} />}
    {aba === 'disputas' && <Colecao estado={disputas} carregando={carregandoAba} erro={erroAba} vazio="Sem disputas." renderizar={itens => <div className="space-y-2">{itens.map(d => <article key={d.disputaId} className="rounded-lg border p-3 text-sm"><div className="flex flex-wrap justify-between gap-2"><strong>{d.codigoPublico}</strong><Link className="text-primary underline" to={`/dashboard/disputas/${d.disputaId}`}>Ver disputa</Link></div><p className="mt-1">{d.clienteNome} · {d.tipo} · criada em {formatarData(d.criadoEm)}</p><div className="mt-2 flex gap-2"><EtiquetaEstado estado={d.estado}/><span className="text-muted-foreground">Atualizada: {formatarData(d.atualizadoEm)}</span></div></article>)}</div>} aoPaginar={offset => void carregarAba('disputas',offset)} />}
    {aba === 'atividade' && <BlocoAdmin titulo="Atividade e outros papéis"><div className="grid gap-4 sm:grid-cols-3"><CampoAdmin rotulo="Visualizações" valor={metricas.visualizacoes}/><CampoAdmin rotulo="Cliques WhatsApp" valor={metricas.cliquesWhatsapp}/><CampoAdmin rotulo="Contactos recebidos" valor={metricas.contactosRecebidos}/></div><div className="mt-5 flex flex-wrap gap-2">{detalhe.outrosPapeis.cliente && <Link className="rounded border border-primary px-3 py-2 text-sm text-primary" to={`/dashboard/compradores/${vendedor.userId}`}>Abrir Comprador 360</Link>}{detalhe.outrosPapeis.parceiroEntrega && <span className="rounded border px-3 py-2 text-sm"><Truck className="mr-1 inline size-4"/>Também é parceiro de entrega</span>}{detalhe.outrosPapeis.admin && <span className="rounded border px-3 py-2 text-sm">Administrador</span>}</div></BlocoAdmin>}
    {aba === 'historico' && <Colecao estado={historico} carregando={carregandoAba} erro={erroAba} vazio="Sem histórico documental." renderizar={itens => <div className="space-y-2">{itens.map((e,index) => <article key={`${e.documentoId}-${index}`} className="rounded-lg border p-3 text-sm"><strong>{rotuloEstado(e.evento)}</strong><p className="mt-1">{rotuloEstado(e.estadoAnterior)} → {rotuloEstado(e.estadoNovo)} · {formatarData(e.criadoEm)}</p>{e.motivoRejeicao && <p className="mt-1 text-destructive">Motivo: {e.motivoRejeicao}</p>}</article>)}</div>} aoPaginar={offset => void carregarAba('historico',offset)} />}
  </div>;
}
function Avatar({nome,foto}:{nome:string;foto:string|null}) { return foto ? <img src={foto} alt={`Foto de ${nome}`} className="relative z-10 size-20 rounded-full border-4 border-white/30 object-cover"/> : <span className="relative z-10 flex size-20 items-center justify-center rounded-full bg-white/15 text-3xl font-bold text-primary-foreground">{nome.charAt(0).toUpperCase() || '?'}</span>; }
function Visao({detalhe,aoHistorico}:{detalhe:DetalheVendedorAdmin;aoHistorico:()=>void}) { const comerciais = Object.entries(detalhe.dadosComerciais).map(([chave,valor])=>({chave,valor:valorComercial(valor)})).filter(item=>item.valor); return <><section className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3"><Metrica texto="Produtos" valor={detalhe.resumo.totalProdutos}/><Metrica texto="Serviços" valor={detalhe.resumo.totalServicos}/><Metrica texto="Encomendas" valor={detalhe.resumo.totalEncomendas}/><Metrica texto="Pagamentos" valor={detalhe.resumo.totalPagamentos}/><Metrica texto="Disputas" valor={detalhe.resumo.totalDisputas}/><Metrica texto="Eventos documentais" valor={detalhe.resumo.totalEventosDocumentais}/></section><BlocoAdmin titulo="Dados comerciais">{comerciais.length ? <dl className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{comerciais.map(item=><CampoAdmin key={item.chave} rotulo={rotulosComerciais[item.chave] || item.chave} valor={item.valor}/>)}</dl> : <p className="text-sm text-muted-foreground">Sem dados comerciais adicionais.</p>}</BlocoAdmin><BlocoAdmin titulo="Documentos">{detalhe.documentos.length ? <div className="space-y-3">{detalhe.documentos.map(d=><article key={d.documentoId} className="rounded-lg border p-3 text-sm"><div className="flex flex-wrap items-center gap-2"><strong>{d.tipo}</strong><EtiquetaEstado estado={d.estado}/></div><p className="mt-2">N.º: {d.numero || '—'} · Validade: {formatarData(d.validade)} · Enviado: {formatarData(d.criadoEm)}</p><p className="mt-1 text-muted-foreground">Frente: {d.frenteDisponivel?'Disponível':'Não enviada'} · Verso: {d.versoDisponivel?'Disponível':'Não enviado'} · Analisado: {formatarData(d.analisadoEm)}</p>{d.motivoRejeicao && <p className="mt-1 text-destructive">Motivo: {d.motivoRejeicao}</p>}</article>)}</div> : <p className="text-sm text-muted-foreground">Sem documentos.</p>}</BlocoAdmin><BlocoAdmin titulo="Histórico documental recente">{detalhe.historicoDocumentalRecente.length ? <div className="space-y-2">{detalhe.historicoDocumentalRecente.map((e,index)=><p key={`${e.documentoId}-${index}`} className="border-b pb-2 text-sm">{rotuloEstado(e.evento)} · {formatarData(e.criadoEm)}</p>)}</div> : <p className="text-sm text-muted-foreground">Sem histórico documental.</p>}<button onClick={aoHistorico} className="mt-3 inline-flex items-center gap-1 text-sm font-semibold text-primary"><FileText className="size-4"/>Ver histórico completo</button></BlocoAdmin></>; }
function Financeiro({financeiro}:{financeiro:DetalheVendedorAdmin['financeiro']}) { return <BlocoAdmin titulo="Resumo financeiro"><p className="mb-4 text-sm text-muted-foreground">Volume bruto não representa receita da ANGROLINK. Os valores são calculados exclusivamente no servidor.</p><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3"><CampoAdmin rotulo="Total de encomendas" valor={financeiro.totalEncomendas}/><CampoAdmin rotulo="Total de pagamentos" valor={financeiro.totalPagamentos}/><CampoAdmin rotulo="Volume bruto transacionado" valor={formatarKz(financeiro.gmvBrutoCentimos)}/><CampoAdmin rotulo="Volume efetivo após reembolsos" valor={formatarKz(financeiro.gmvEfetivoCentimos)}/><CampoAdmin rotulo="Comissão ANGROLINK" valor={formatarKz(financeiro.comissaoCentimos)}/><CampoAdmin rotulo="Valor efetivo do vendedor" valor={formatarKz(financeiro.valorVendedorCentimos)}/><CampoAdmin rotulo="Reembolsos" valor={formatarKz(financeiro.reembolsosCentimos)}/><CampoAdmin rotulo="Pagamentos pendentes / confirmados" valor={`${financeiro.pagamentosPendentes} / ${financeiro.pagamentosConfirmados}`}/><CampoAdmin rotulo="Repasses pendentes / concluídos" valor={`${financeiro.repassesPendentes} / ${financeiro.repassesConcluidos}`}/></div></BlocoAdmin>; }
function Colecao<T>({estado,carregando,erro,vazio,renderizar,aoPaginar}:{estado:PaginaAdmin<T>|null;carregando:boolean;erro:string|null;vazio:string;renderizar:(itens:T[])=>ReactNode;aoPaginar:(offset:number)=>void}) { if(carregando) return <p className="painel-dashboard-form text-sm text-muted-foreground">A carregar…</p>; if(erro) return <div className="painel-dashboard-form text-sm text-destructive">{erro}</div>; if(!estado) return null; return <BlocoAdmin titulo="">{estado.itens.length?renderizar(estado.itens):<p className="text-sm text-muted-foreground">{vazio}</p>}<Paginacao pagina={estado as PaginaAdmin<unknown>} aoMudar={aoPaginar}/></BlocoAdmin>; }
function Metrica({texto,valor}:{texto:string;valor:number}) { return <div className="rounded-xl border bg-card p-4"><p className="text-xs text-muted-foreground">{texto}</p><p className="mt-1 font-titulo text-2xl font-bold text-primary">{valor}</p></div>; }
