import { useCallback, useEffect, useState } from 'react';
import { Link, useNavigate, useParams } from 'react-router-dom';
import { ArrowLeft, ExternalLink, FileCheck2, Heart, MessageSquare, ShoppingBag } from 'lucide-react';
import { obterCompradorAdmin, type DetalheCompradorAdmin } from '@/services/adminCompradores';
import { BlocoAdmin, CampoAdmin, EtiquetaEstado, formatarData, formatarKz, rotuloEstado } from './admin360Util';

type Aba = 'visao' | 'encomendas' | 'financeiro' | 'disputas' | 'atividade';
const abas: Array<{ valor: Aba; texto: string }> = [{ valor: 'visao', texto: 'Visão geral' }, { valor: 'encomendas', texto: 'Encomendas' }, { valor: 'financeiro', texto: 'Financeiro' }, { valor: 'disputas', texto: 'Disputas' }, { valor: 'atividade', texto: 'Atividade' }];

export default function AdminCompradorDetalhe() {
  const { id } = useParams(); const navegar = useNavigate(); const [detalhe, setDetalhe] = useState<DetalheCompradorAdmin | null>(null); const [aba, setAba] = useState<Aba>('visao'); const [aCarregar, setACarregar] = useState(true); const [erro, setErro] = useState(false);
  const carregar = useCallback(async () => { if (!id) { setErro(true); setACarregar(false); return; } try { setErro(false); setDetalhe(await obterCompradorAdmin(id)); } catch { setErro(true); } finally { setACarregar(false); } }, [id]);
  useEffect(() => { void carregar(); }, [carregar]);
  if (aCarregar) return <p className="painel-dashboard-form text-sm text-muted-foreground">A carregar comprador…</p>;
  if (erro || !detalhe) return <div className="painel-dashboard-form border-destructive/30"><p className="font-semibold text-destructive">Comprador não encontrado ou indisponível.</p><button onClick={() => void carregar()} className="mt-3 rounded-md border border-destructive px-3 py-2 text-xs font-semibold text-destructive">Tentar novamente</button></div>;
  const { comprador, resumo } = detalhe;
  return <div className="space-y-5"><button onClick={() => navegar('/dashboard/compradores')} className="inline-flex items-center gap-1 text-sm text-muted-foreground hover:text-primary"><ArrowLeft className="size-4" />Voltar aos compradores</button>
    <header className="painel-dashboard-cabecalho flex flex-col gap-4 sm:flex-row sm:items-center"><Avatar nome={comprador.nome} fotoUrl={comprador.fotoUrl} /><div className="relative z-10 min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><h1 className="font-titulo text-2xl font-bold text-primary-foreground">{comprador.nome}</h1><Etiqueta texto={comprador.tipoComprador === 'negocio' ? 'Negócio' : 'Casa'} /><Etiqueta texto={comprador.contaAtiva ? 'Conta ativa' : 'Conta inativa'} /></div><p className="mt-2 break-words text-sm text-primary-foreground/85">{comprador.email || 'Sem e-mail'} · {comprador.telefone || 'Sem telefone'}</p><p className="mt-1 text-sm text-primary-foreground/80">{[comprador.municipio, comprador.provincia].filter(Boolean).join(', ') || 'Localização não indicada'} · Registado em {formatarData(comprador.criadoEm)}</p></div></header>
    {detalhe.outrosPapeis.length > 0 && <section className="rounded-xl border border-border bg-card p-4"><p className="text-sm font-semibold">Também possui perfil como</p><div className="mt-2 flex flex-wrap gap-2">{detalhe.outrosPapeis.map(papel => <Etiqueta key={`${papel.papel}-${papel.id}`} texto={`${rotuloPapel(papel.papel)} — ${rotuloEstado(papel.estado)}`} />)}</div></section>}
    <nav className="flex gap-2 overflow-x-auto border-b pb-2" aria-label="Secções do comprador">{abas.map(item => <button key={item.valor} onClick={() => setAba(item.valor)} className={`shrink-0 rounded-md px-3 py-2 text-sm font-semibold ${aba === item.valor ? 'bg-primary text-primary-foreground' : 'text-muted-foreground hover:bg-muted'}`}>{item.texto}</button>)}</nav>
    {aba === 'visao' && <><section className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3"><Metrica texto="Total de encomendas" valor={resumo.totalEncomendas} /><Metrica texto="Concluídas" valor={resumo.encomendasConcluidas} /><Metrica texto="Canceladas" valor={resumo.encomendasCanceladas} /><Metrica texto="Recusadas pelo vendedor" valor={resumo.recusasVendedor} /><Metrica texto="Disputas" valor={resumo.totalDisputas} /><Metrica texto="Pagamentos" valor={resumo.totalPagamentos} /></section><BlocoAdmin titulo="Dados do comprador"><dl className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3"><CampoAdmin rotulo="Estado" valor={comprador.contaAtiva ? 'Ativa' : 'Inativa'} /><CampoAdmin rotulo="Última atividade" valor={formatarData(comprador.ultimaAtividadeEm)} /><CampoAdmin rotulo="Verificação" valor="Não aplicável para compradores comuns" /></dl></BlocoAdmin></>}
    {aba === 'encomendas' && <section className="space-y-5"><ListaEncomendas detalhe={detalhe} /><ListaMotivos titulo="Cancelamentos do comprador" itens={detalhe.cancelamentos} data="canceladoEm" vazio="Sem cancelamentos iniciados pelo comprador." /><ListaMotivos titulo="Recusas de vendedores" itens={detalhe.recusasVendedor} data="recusadoEm" vazio="Sem recusas de vendedores." /></section>}
    {aba === 'financeiro' && <ListaPagamentos detalhe={detalhe} />}
    {aba === 'disputas' && <ListaDisputas detalhe={detalhe} />}
    {aba === 'atividade' && <BlocoAdmin titulo="Atividade agregada"><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><CampoAdmin rotulo="Contactos por produtos" valor={detalhe.atividade.contactosProdutos} /><CampoAdmin rotulo="Contactos por serviços" valor={detalhe.atividade.contactosServicos} /><CampoAdmin rotulo="Favoritos" valor={detalhe.atividade.favoritos} /><CampoAdmin rotulo="Última atividade" valor={formatarData(detalhe.atividade.ultimaAtividadeEm)} /></div><p className="mt-5 text-xs text-muted-foreground">Esta área apresenta apenas indicadores úteis para suporte e resolução de problemas.</p></BlocoAdmin>}
  </div>;
}

function ListaEncomendas({ detalhe }: { detalhe: DetalheCompradorAdmin }) { return <BlocoAdmin titulo="Encomendas">{detalhe.encomendas.length === 0 ? <Vazio texto="Sem encomendas." /> : <div className="space-y-3">{detalhe.encomendas.map(item => <div key={item.encomendaId} className="rounded-xl border p-3"><div className="flex flex-wrap items-start justify-between gap-2"><div><p className="font-semibold">{item.codigoPublico}</p><p className="text-sm text-muted-foreground">{item.vendedorNome} · {formatarData(item.criadoEm)}</p></div><EtiquetaEstado estado={item.estado} /></div><div className="mt-3 grid gap-2 text-sm sm:grid-cols-4"><p>{formatarKz(item.totalCentimos)}</p><p>{rotuloEstado(item.modalidade)}</p><p>Pagamento: {rotuloEstado(item.estadoPagamento)}</p><p>{item.temDisputa ? 'Com disputa' : 'Sem disputa'}</p></div><Link to={`/dashboard/encomendas/${item.encomendaId}`} className="mt-3 inline-flex items-center gap-1 text-sm font-semibold text-primary hover:underline">Abrir encomenda <ExternalLink className="size-4" /></Link></div>)}</div>}</BlocoAdmin>; }
function ListaMotivos({ titulo, itens, data, vazio }: { titulo: string; itens: Array<{ encomendaId: string; codigoPublico: string; vendedorNome: string; motivo: string | null; canceladoEm?: string | null; recusadoEm?: string | null }>; data: 'canceladoEm' | 'recusadoEm'; vazio: string }) { return <BlocoAdmin titulo={titulo}>{itens.length === 0 ? <Vazio texto={vazio} /> : <div className="space-y-2">{itens.map(item => <div key={item.encomendaId} className="rounded-lg border border-border p-3 text-sm"><p className="font-semibold">{item.codigoPublico} · {item.vendedorNome}</p><p className="mt-1 break-words text-muted-foreground">Motivo: {item.motivo || 'Não informado'}</p><p className="mt-1 text-xs text-muted-foreground">{formatarData(data === 'canceladoEm' ? item.canceladoEm : item.recusadoEm)}</p></div>)}</div>}</BlocoAdmin>; }
function ListaPagamentos({ detalhe }: { detalhe: DetalheCompradorAdmin }) { return <BlocoAdmin titulo="Pagamentos">{detalhe.pagamentos.length === 0 ? <Vazio texto="Sem pagamentos associados." /> : <div className="space-y-3">{detalhe.pagamentos.map(item => <div key={item.pagamentoId} className="rounded-xl border p-3"><div className="flex flex-wrap justify-between gap-2"><div><p className="font-semibold">{item.codigoPublico}</p><p className="text-xs text-muted-foreground">{formatarData(item.criadoEm)}</p></div><EtiquetaEstado estado={item.estado} /></div><div className="mt-3 grid gap-2 text-sm sm:grid-cols-3"><p>Total: <strong>{formatarKz(item.totalCentimos)}</strong></p><p>Método: {item.metodo ? rotuloEstado(item.metodo) : <span className="text-amber-700">Inconsistente/não disponível</span>}</p><p>Reembolsado: {formatarKz(item.totalReembolsadoCentimos)}</p></div><div className="mt-3 flex flex-wrap gap-3"><Link to={`/dashboard/encomendas/${item.encomendaId}`} className="inline-flex items-center gap-1 text-sm font-semibold text-primary hover:underline">Abrir encomenda <ExternalLink className="size-4" /></Link><Link to="/dashboard/financeiro" className="text-sm font-semibold text-primary hover:underline">Ver Financeiro</Link></div></div>)}</div>}</BlocoAdmin>; }
function ListaDisputas({ detalhe }: { detalhe: DetalheCompradorAdmin }) { return <BlocoAdmin titulo="Disputas">{detalhe.disputas.length === 0 ? <Vazio texto="Sem disputas." /> : <div className="space-y-3">{detalhe.disputas.map(item => <div key={item.disputaId} className="rounded-xl border p-3"><div className="flex flex-wrap justify-between gap-2"><div><p className="font-semibold">{item.codigoPublico} · {item.vendedorNome}</p><p className="mt-1 text-sm capitalize text-muted-foreground">{rotuloEstado(item.tipo)} · {formatarData(item.criadoEm)}</p></div><EtiquetaEstado estado={item.estado} /></div><Link to={`/dashboard/disputas/${item.disputaId}`} className="mt-3 inline-flex items-center gap-1 text-sm font-semibold text-primary hover:underline">Abrir disputa <ExternalLink className="size-4" /></Link></div>)}</div>}</BlocoAdmin>; }
function Metrica({ texto, valor }: { texto: string; valor: number }) { return <div className="rounded-xl border bg-card p-4"><p className="font-titulo text-2xl font-bold text-primary">{valor}</p><p className="mt-1 text-sm text-muted-foreground">{texto}</p></div>; }
function Vazio({ texto }: { texto: string }) { return <p className="py-5 text-sm text-muted-foreground">{texto}</p>; }
function Avatar({ nome, fotoUrl }: { nome: string; fotoUrl: string | null }) { return fotoUrl ? <img src={fotoUrl} alt={`Foto de ${nome}`} className="relative z-10 size-16 rounded-full border-4 border-white object-cover shadow" /> : <span className="relative z-10 flex size-16 items-center justify-center rounded-full bg-primary-foreground/15 font-titulo text-2xl font-bold text-primary-foreground">{nome.trim().charAt(0).toUpperCase() || '?'}</span>; }
function Etiqueta({ texto }: { texto: string }) { return <span className="rounded-full border border-primary-foreground/30 bg-primary-foreground/10 px-2 py-0.5 text-xs font-semibold text-primary-foreground">{texto}</span>; }
function rotuloPapel(papel: string) { return papel === 'parceiro_entrega' ? 'Entregador' : papel === 'vendedor' ? 'Vendedor' : 'Administrador'; }
