import type { Json } from '@/types/database.types';
import { supabase } from './supabase';

type Obj = Record<string, Json | undefined>;
export interface Pagina<T> { itens: T[]; paginacao: { totalResultados: number; limite: number; offset: number } }
export interface Parceiro360 { parceiroId: string; userId: string; nome: string; email: string | null; telefone: string; fotoDisponivel: boolean; criadoEm: string; atualizadoEm: string; estado: string; disponibilidade: boolean; aprovadoEm: string | null; motivoRejeicao: string | null; motivoSuspensao: string | null; provincia: string; municipio: string; bairro: string | null; zonaBase: string | null }
export interface ElegibilidadeLogistica { podeReceberEntregas: boolean; motivos: string[]; veiculos: Array<{ veiculoId: string; operacional: boolean; motivos: string[] }> }
export interface DetalheEntregador { parceiro: Parceiro360; resumo: { totalVeiculos: number; veiculosAprovados: number; totalDocumentos: number; documentosPendentes: number; documentosExpirados: number; areasAtivas: number }; outrosPapeis: { cliente: boolean; vendedor: boolean; admin: boolean }; elegibilidadeLogistica: ElegibilidadeLogistica; historicoDocumentalDisponivel: boolean; historicoAdministrativoDisponivel: boolean; entregasDisponiveis: boolean; financeiroDisponivel: boolean }
export interface Veiculo { veiculoId: string; tipo: string; marca: string; modelo: string; cor: string; ano: number | null; matricula: string; carroceria: string | null; capacidadeKg: number; volumeM3: number | null; caixa: boolean; paletes: boolean; refrigeracao: boolean; estado: string; motivo: string | null; fotoDisponivel: boolean; criadoEm: string; atualizadoEm: string }
export interface Documento { documentoId: string; tipo: string; numero: string | null; validade: string | null; estado: string; veiculoId: string | null; matricula: string | null; frenteDisponivel: boolean; versoDisponivel: boolean; criadoEm: string; atualizadoEm: string; analisadoPor: string | null; analisadoEm: string | null; motivo: string | null }
export interface Area { areaId: string; provincia: string; municipio: string; bairro: string | null; ativa: boolean; criadoEm: string }
export interface VersaoDocumentoHistorico { versaoId: string; numeroVersao: number; estado: string; numero: string | null; validade: string | null; criadoEm: string; analisadoPor: string | null; analisadoEm: string | null; motivo: string | null; substituidoEm: string | null; frenteDisponivel: boolean; versoDisponivel: boolean }
export interface EventoDocumentoHistorico { eventoId: string; versaoId: string | null; atorTipo: string; utilizadorId: string | null; evento: string; estadoAnterior: string | null; estadoNovo: string | null; motivo: string | null; criadoEm: string }
export interface DocumentoHistorico { documentoId: string; tipo: string; veiculoId: string | null; matricula: string | null; versaoAtualId: string | null; versaoAtual: number | null; totalVersoes: number; estadoAtual: string; validadeAtual: string | null; atualizadoEm: string; versoes: VersaoDocumentoHistorico[]; eventos: EventoDocumentoHistorico[] }

const obj = (v: Json | null | undefined): Obj | null => v !== null && typeof v === 'object' && !Array.isArray(v) ? v as Obj : null;
const arr = (v: Json | undefined) => Array.isArray(v) ? v : [];
const s = (o: Obj, k: string) => typeof o[k] === 'string' ? o[k] as string : null;
const n = (o: Obj, k: string) => typeof o[k] === 'number' ? o[k] as number : null;
const b = (o: Obj, k: string) => typeof o[k] === 'boolean' ? o[k] as boolean : null;
const rs = (o: Obj, k: string) => { const v = s(o, k); if (v === null) throw Error('Resposta administrativa incompleta.'); return v; };
const rn = (o: Obj, k: string) => { const v = n(o, k); if (v === null) throw Error('Resposta administrativa incompleta.'); return v; };
const rb = (o: Obj, k: string) => { const v = b(o, k); if (v === null) throw Error('Resposta administrativa incompleta.'); return v; };
const textos = (v: Json | undefined) => arr(v).filter((item): item is string => typeof item === 'string');

function pagina<T>(v: Json, map: (x: Json) => T | null): Pagina<T> { const r = obj(v), p = obj(r?.paginacao); if (!r || !p) throw Error('Resposta paginada inválida.'); return { itens: arr(r.itens).map(map).filter((x): x is T => x !== null), paginacao: { totalResultados: rn(p, 'total_resultados'), limite: rn(p, 'limite'), offset: rn(p, 'offset') } }; }
function veiculo(v: Json): Veiculo | null { const o = obj(v); if (!o) return null; try { return { veiculoId: rs(o, 'veiculo_id'), tipo: rs(o, 'tipo_veiculo'), marca: rs(o, 'marca'), modelo: rs(o, 'modelo'), cor: rs(o, 'cor'), ano: n(o, 'ano'), matricula: rs(o, 'matricula'), carroceria: s(o, 'tipo_carrocaria'), capacidadeKg: rn(o, 'capacidade_kg'), volumeM3: n(o, 'capacidade_volume_m3'), caixa: rb(o, 'possui_caixa_carga'), paletes: rb(o, 'aceita_paletes'), refrigeracao: rb(o, 'possui_refrigeracao'), estado: rs(o, 'estado_verificacao'), motivo: s(o, 'motivo_rejeicao'), fotoDisponivel: rb(o, 'foto_disponivel'), criadoEm: rs(o, 'criado_em'), atualizadoEm: rs(o, 'atualizado_em') }; } catch { return null; } }
function documento(v: Json): Documento | null { const o = obj(v); if (!o) return null; try { return { documentoId: rs(o, 'documento_id'), tipo: rs(o, 'tipo_documento'), numero: s(o, 'numero_documento'), validade: s(o, 'validade'), estado: rs(o, 'estado'), veiculoId: s(o, 'veiculo_id'), matricula: s(o, 'veiculo_matricula'), frenteDisponivel: rb(o, 'frente_disponivel'), versoDisponivel: rb(o, 'verso_disponivel'), criadoEm: rs(o, 'criado_em'), atualizadoEm: rs(o, 'atualizado_em'), analisadoPor: s(o, 'analisado_por'), analisadoEm: s(o, 'analisado_em'), motivo: s(o, 'motivo_rejeicao') }; } catch { return null; } }
function area(v: Json): Area | null { const o = obj(v); if (!o) return null; try { return { areaId: rs(o, 'area_id'), provincia: rs(o, 'provincia'), municipio: rs(o, 'municipio'), bairro: s(o, 'bairro'), ativa: rb(o, 'ativo'), criadoEm: rs(o, 'criado_em') }; } catch { return null; } }
function versaoHistorico(v: Json): VersaoDocumentoHistorico | null { const o = obj(v); if (!o) return null; try { return { versaoId: rs(o, 'versao_id'), numeroVersao: rn(o, 'numero_versao'), estado: rs(o, 'estado'), numero: s(o, 'numero_documento'), validade: s(o, 'validade'), criadoEm: rs(o, 'criado_em'), analisadoPor: s(o, 'analisado_por'), analisadoEm: s(o, 'analisado_em'), motivo: s(o, 'motivo_rejeicao'), substituidoEm: s(o, 'substituido_em'), frenteDisponivel: rb(o, 'frente_disponivel'), versoDisponivel: rb(o, 'verso_disponivel') }; } catch { return null; } }
function eventoHistorico(v: Json): EventoDocumentoHistorico | null { const o = obj(v); if (!o) return null; try { return { eventoId: rs(o, 'evento_id'), versaoId: s(o, 'versao_id'), atorTipo: rs(o, 'ator_tipo'), utilizadorId: s(o, 'utilizador_id'), evento: rs(o, 'evento'), estadoAnterior: s(o, 'estado_anterior'), estadoNovo: s(o, 'estado_novo'), motivo: s(o, 'motivo'), criadoEm: rs(o, 'criado_em') }; } catch { return null; } }
function documentoHistorico(v: Json): DocumentoHistorico | null { const o = obj(v); if (!o) return null; try { return { documentoId: rs(o, 'documento_id'), tipo: rs(o, 'tipo_documento'), veiculoId: s(o, 'veiculo_id'), matricula: s(o, 'veiculo_matricula'), versaoAtualId: s(o, 'versao_atual_id'), versaoAtual: n(o, 'versao_atual'), totalVersoes: rn(o, 'total_versoes'), estadoAtual: rs(o, 'estado_atual'), validadeAtual: s(o, 'validade_atual'), atualizadoEm: rs(o, 'atualizado_em'), versoes: arr(o.versoes).map(versaoHistorico).filter((x): x is VersaoDocumentoHistorico => x !== null), eventos: arr(o.eventos).map(eventoHistorico).filter((x): x is EventoDocumentoHistorico => x !== null) }; } catch { return null; } }
async function lista<T>(rpc: 'listar_veiculos_entregador_admin' | 'listar_documentos_entregador_admin' | 'listar_areas_cobertura_entregador_admin' | 'listar_historico_documental_entregador_admin', id: string, limite: number, offset: number, map: (x: Json) => T | null) { const { data, error } = await supabase.rpc(rpc, { p_parceiro_id: id, p_limite: limite, p_offset: offset }); if (error) throw Error('Não foi possível carregar esta secção.'); return pagina(data, map); }

export async function obterEntregadorAdmin(id: string): Promise<DetalheEntregador> {
  const { data, error } = await supabase.rpc('obter_entregador_admin', { p_parceiro_id: id });
  if (error) throw Error('Não foi possível carregar o entregador.');
  const r = obj(data), p = obj(r?.parceiro), x = obj(r?.resumo_operacional), o = obj(r?.outros_papeis), e = obj(r?.elegibilidade_logistica) || { pode_receber_entregas: false, motivos: ['elegibilidade_indisponivel'], veiculos: [] };
  if (!r || !p || !x || !o) throw Error('Resposta administrativa incompleta.');
  const veiculosElegibilidade = arr(e.veiculos).map(item => { const veiculo = obj(item); if (!veiculo) return null; try { return { veiculoId: rs(veiculo, 'veiculo_id'), operacional: rb(veiculo, 'veiculo_operacional'), motivos: textos(veiculo.motivos) }; } catch { return null; } }).filter((item): item is { veiculoId: string; operacional: boolean; motivos: string[] } => item !== null);
  return { parceiro: { parceiroId: rs(p, 'parceiro_id'), userId: rs(p, 'user_id'), nome: rs(p, 'nome_completo'), email: s(p, 'email'), telefone: rs(p, 'telefone'), fotoDisponivel: rb(p, 'foto_perfil_disponivel'), criadoEm: rs(p, 'criado_em'), atualizadoEm: rs(p, 'atualizado_em'), estado: rs(p, 'estado'), disponibilidade: rb(p, 'disponibilidade'), aprovadoEm: s(p, 'aprovado_em'), motivoRejeicao: s(p, 'motivo_rejeicao'), motivoSuspensao: s(p, 'motivo_suspensao'), provincia: rs(p, 'provincia'), municipio: rs(p, 'municipio'), bairro: s(p, 'bairro'), zonaBase: s(p, 'zona_base') }, resumo: { totalVeiculos: rn(x, 'total_veiculos'), veiculosAprovados: rn(x, 'veiculos_aprovados'), totalDocumentos: rn(x, 'total_documentos'), documentosPendentes: rn(x, 'documentos_pendentes'), documentosExpirados: rn(x, 'documentos_expirados'), areasAtivas: rn(x, 'areas_ativas') }, outrosPapeis: { cliente: rb(o, 'cliente'), vendedor: rb(o, 'vendedor'), admin: rb(o, 'admin') }, elegibilidadeLogistica: { podeReceberEntregas: rb(e, 'pode_receber_entregas'), motivos: textos(e.motivos), veiculos: veiculosElegibilidade }, historicoDocumentalDisponivel: rb(r, 'historico_documental_disponivel'), historicoAdministrativoDisponivel: rb(r, 'historico_administrativo_disponivel'), entregasDisponiveis: rb(r, 'entregas_disponiveis'), financeiroDisponivel: rb(r, 'financeiro_disponivel') };
}

export const listarVeiculosEntregadorAdmin = (id: string, l = 20, o = 0) => lista('listar_veiculos_entregador_admin', id, l, o, veiculo);
export const listarDocumentosEntregadorAdmin = (id: string, l = 20, o = 0) => lista('listar_documentos_entregador_admin', id, l, o, documento);
export const listarAreasCoberturaEntregadorAdmin = (id: string, l = 20, o = 0) => lista('listar_areas_cobertura_entregador_admin', id, l, o, area);
export const listarHistoricoDocumentalEntregadorAdmin = (id: string, l = 20, o = 0) => lista('listar_historico_documental_entregador_admin', id, l, o, documentoHistorico);
