/**
 * Projeção segura da tabela de vendedores.
 *
 * A coluna `documentos` contém dados sensíveis e nunca deve fazer parte de
 * leituras normais do perfil comercial, mesmo para administradores. Os
 * documentos são consultados pela camada dedicada de documentos.
 */
export const COLUNAS_VENDEDOR_SEM_DOCUMENTOS = [
  'id',
  'user_id',
  'nome_comercial',
  'nome_responsavel',
  'descricao',
  'email',
  'email_login',
  'telefone_whatsapp',
  'whatsapp',
  'indicativo_telefone',
  'telefone_nacional',
  'provincia',
  'municipio',
  'bairro',
  'mercado_bairro',
  'endereco_detalhado',
  'tipo_vendedor',
  'plano',
  'verificado',
  'status_aprovacao',
  'motivo_rejeicao',
  'conta_ativa',
  'pode_destacar',
  'aprovado_em',
  'aprovado_por',
  'foto_perfil',
  'ano_inicio',
  'data_inicio_atividade',
  'horario_atendimento',
  'entrega_disponivel',
  'tipo_producao',
  'area_cultivada',
  'principais_culturas',
  'producao_mensal',
  'venda_grosso',
  'venda_retalho',
  'tipos_produtos',
  'compra_produtores',
  'volume_minimo',
  'entrega_outras_provincias',
  'tipo_loja',
  'mercado_localizado',
  'venda_presencial',
  'proximo_destaque_produto_em',
  'proximo_destaque_servico_em',
  'criado_em',
  'atualizado_em',
].join(', ');
