import { useCallback, useEffect, useState } from 'react';
import { useNavigate, useParams } from 'react-router-dom';
import { ArrowLeft, KeyRound } from 'lucide-react';
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from '@/components/ui/dialog';
import { EncomendaDetalheConteudo } from '@/componentes/encomendas/EncomendaDetalheConteudo';
import { useAuth } from '@/contextos/AuthContexto';
import { useEncomendasTempoReal } from '@/hooks/useEncomendasTempoReal';
import { useToast } from '@/hooks/use-toast';
import { fetchDetalheEncomenda, transicionarEncomendaLevantamento, validarCodigoLevantamento, type DetalheEncomenda } from '@/services/encomendas';

export default function VendedorEncomendaDetalhe() {
  const { id } = useParams(); const nav = useNavigate(); const { toast } = useToast(); const { utilizador } = useAuth();
  const [encomenda, setEncomenda] = useState<DetalheEncomenda | null>(null); const [loading, setLoading] = useState(true); const [recusar, setRecusar] = useState(false); const [motivo, setMotivo] = useState(''); const [codigo, setCodigo] = useState(''); const [acao, setAcao] = useState(false);
  const carregar = useCallback(async () => { if (!id) return; try { setEncomenda(await fetchDetalheEncomenda(id)); } catch { toast({ title: 'Não foi possível carregar a encomenda.', variant: 'destructive' }); } finally { setLoading(false); } }, [id, toast]);
  useEffect(() => { void carregar(); }, [carregar]);
  useEncomendasTempoReal({ ativo: utilizador?.papel === 'vendedor', encomendaId: id }, carregar);
  const mudar = async (estado: string, motivoAcao?: string) => { if (!encomenda) return; try { setAcao(true); await transicionarEncomendaLevantamento(encomenda.id, estado, motivoAcao); toast({ title: 'Encomenda atualizada.' }); setRecusar(false); await carregar(); } catch { toast({ title: 'Não foi possível atualizar a encomenda.', variant: 'destructive' }); } finally { setAcao(false); } };
  const validar = async () => { if (!encomenda) return; try { setAcao(true); const resultado = await validarCodigoLevantamento(encomenda.id, codigo); if (resultado.validado) { setCodigo(''); toast({ title: 'Levantamento confirmado.' }); await carregar(); } else toast({ title: resultado.motivo || 'Código incorreto.', description: resultado.bloqueado ? 'O cliente deve gerar um novo código.' : `Tentativas restantes: ${resultado.tentativas_restantes}`, variant: 'destructive' }); } catch { toast({ title: 'Não foi possível validar o código.', variant: 'destructive' }); } finally { setAcao(false); } };
  if (loading) return <p className="painel-dashboard-form text-sm text-muted-foreground">A carregar encomenda…</p>;
  if (!encomenda) return <p className="painel-dashboard-form text-sm text-muted-foreground">Encomenda não encontrada.</p>;
  return <div className="space-y-5"><button onClick={() => nav('/dashboard/encomendas')} className="inline-flex items-center gap-1 text-sm text-muted-foreground hover:text-green-800"><ArrowLeft className="size-4" />Voltar às encomendas</button><EncomendaDetalheConteudo encomenda={encomenda} contexto="vendedor" />{encomenda.estado === 'aguardando_confirmacao' && <div className="flex flex-wrap gap-3"><button disabled={acao} onClick={() => void mudar('confirmada')} className="rounded-lg bg-green-800 px-4 py-2 text-sm font-semibold text-white">Confirmar encomenda</button><button onClick={() => setRecusar(true)} className="rounded-lg border border-red-300 px-4 py-2 text-sm font-semibold text-red-700">Recusar</button></div>}{encomenda.estado === 'confirmada' && <button disabled={acao} onClick={() => void mudar('em_preparacao')} className="rounded-lg bg-green-800 px-4 py-2 text-sm font-semibold text-white">Iniciar preparação</button>}{encomenda.estado === 'em_preparacao' && <button disabled={acao} onClick={() => void mudar('pronta_para_levantamento')} className="rounded-lg bg-green-800 px-4 py-2 text-sm font-semibold text-white">Marcar como pronta para levantamento</button>}{encomenda.estado === 'pronta_para_levantamento' && <section className="rounded-2xl border-2 border-green-200 bg-green-50 p-5"><h2 className="flex items-center gap-2 font-titulo text-lg font-bold text-green-900"><KeyRound className="size-5" />Validar levantamento</h2><p className="mt-1 text-sm text-green-800">Introduza o código apresentado pelo cliente.</p><div className="mt-4 flex flex-col gap-2 sm:flex-row"><input inputMode="numeric" maxLength={6} value={codigo} onChange={(evento) => setCodigo(evento.target.value.replace(/\D/g, '').slice(0, 6))} placeholder="000000" className="rounded-lg border bg-white px-3 py-2 font-mono text-lg tracking-widest" /><button disabled={acao || codigo.length !== 6} onClick={() => void validar()} className="rounded-lg bg-green-800 px-4 py-2 text-sm font-semibold text-white disabled:opacity-50">{acao ? 'A validar…' : 'Validar código'}</button></div></section>}<Dialog open={recusar} onOpenChange={setRecusar}><DialogContent><DialogHeader><DialogTitle>Recusar encomenda</DialogTitle><DialogDescription>Indique o motivo para informar o cliente.</DialogDescription></DialogHeader><textarea value={motivo} onChange={(evento) => setMotivo(evento.target.value)} placeholder="Motivo da recusa" className="min-h-24 w-full rounded-lg border p-3 text-sm" /><DialogFooter><button onClick={() => setRecusar(false)} className="rounded-lg border px-4 py-2 text-sm">Voltar</button><button disabled={acao || !motivo.trim()} onClick={() => void mudar('recusada', motivo)} className="rounded-lg bg-red-600 px-4 py-2 text-sm font-semibold text-white">Recusar encomenda</button></DialogFooter></DialogContent></Dialog></div>;
}
