/**
 * ========================================
 * DADOS MOCK — Simulação para MVP
 * ========================================
 */

import { Vendedor, Produto } from '@/tipos';

export const VENDEDORES_MOCK: Vendedor[] = [
  {
    id: 'v1',
    nome_comercial: 'Horta da Dona Maria',
    nome_responsavel: 'Maria Josefa',
    telefone_whatsapp: '244923456789',
    provincia: 'Luanda',
    municipio: 'Viana',
    mercado_bairro: 'Mercado do Kikolo',
    tipo_vendedor: 'produtor',
    descricao: 'Produtora de hortaliças frescas cultivadas sem químicos. Entrega em Viana e arredores.',
    foto_perfil: '/placeholder.svg',
    capa_loja: '/placeholder.svg',
    verificado: true,
    plano: 'destaque',
    data_inicio_plano: '2026-01-01',
    data_fim_plano: '2026-07-01',
    status_aprovacao: 'aprovado',
    criado_em: '2025-12-15',
  },
  {
    id: 'v2',
    nome_comercial: 'Avícola Bengo',
    nome_responsavel: 'João Pedro',
    telefone_whatsapp: '244912345678',
    provincia: 'Luanda',
    municipio: 'Cacuaco',
    mercado_bairro: 'Zona Industrial',
    tipo_vendedor: 'produtor',
    descricao: 'Frangos de campo, ovos frescos e codornizes. Venda por grosso e retalho.',
    foto_perfil: '/placeholder.svg',
    verificado: true,
    plano: 'premium',
    data_inicio_plano: '2026-02-01',
    data_fim_plano: '2026-08-01',
    status_aprovacao: 'aprovado',
    criado_em: '2026-01-10',
  },
  {
    id: 'v3',
    nome_comercial: 'Cereais do Huambo',
    nome_responsavel: 'António Silva',
    telefone_whatsapp: '244934567890',
    provincia: 'Huambo',
    municipio: 'Huambo',
    mercado_bairro: 'Mercado Central',
    tipo_vendedor: 'grossista',
    descricao: 'Milho, feijão e soja direto do campo. Sacas de 25kg e 50kg.',
    foto_perfil: '/placeholder.svg',
    verificado: false,
    plano: 'gratuito',
    data_inicio_plano: '2026-03-01',
    data_fim_plano: '2026-09-01',
    status_aprovacao: 'aprovado',
    criado_em: '2026-02-20',
  },
  {
    id: 'v4',
    nome_comercial: 'Sumos Naturais Kwanza',
    nome_responsavel: 'Ana Luísa',
    telefone_whatsapp: '244945678901',
    provincia: 'Luanda',
    municipio: 'Belas',
    mercado_bairro: 'Talatona',
    tipo_vendedor: 'mini_mercado',
    descricao: 'Sumos de frutas naturais sem conservantes. Manga, goiaba, maracujá e mais.',
    foto_perfil: '/placeholder.svg',
    verificado: true,
    plano: 'destaque',
    data_inicio_plano: '2026-01-15',
    data_fim_plano: '2026-07-15',
    status_aprovacao: 'aprovado',
    criado_em: '2026-01-05',
  },
  {
    id: 'v5',
    nome_comercial: 'Distribuidor Alimentar Sul',
    nome_responsavel: 'Carlos Mendes',
    telefone_whatsapp: '244956789012',
    provincia: 'Huila',
    municipio: 'Lubango',
    mercado_bairro: 'Mercado da Humpata',
    tipo_vendedor: 'grossista',
    descricao: 'Distribuição por grosso de alimentos secos, conservas e óleos para todo o sul de Angola.',
    foto_perfil: '/placeholder.svg',
    verificado: true,
    plano: 'premium',
    data_inicio_plano: '2026-02-01',
    data_fim_plano: '2026-08-01',
    status_aprovacao: 'aprovado',
    criado_em: '2026-01-20',
  },
];

export const PRODUTOS_MOCK: Produto[] = [
  {
    id: 'p1',
    nome_produto: 'Tomate Cereja Fresco',
    categoria: 'frescos',
    subcategoria: 'Hortaliças',
    preco_aproximado: 1500,
    unidade: 'kg',
    descricao: 'Tomate cereja cultivado sem químicos, colhido diariamente.',
    imagem_principal: '/placeholder.svg',
    imagens_secundarias: ['/placeholder.svg'],
    disponivel: true,
    destaque: true,
    status: 'ativo',
    vendedor_id: 'v1',
    provincia: 'Luanda',
    municipio: 'Viana',
    criado_em: '2026-03-01',
    atualizado_em: '2026-03-01',
    tipo_venda: 'retalho',
    quantidade_minima: 1,
  },
  {
    id: 'p2',
    nome_produto: 'Couve Manteiga',
    categoria: 'frescos',
    subcategoria: 'Hortaliças',
    preco_aproximado: 500,
    unidade: 'unidade',
    descricao: 'Couve manteiga fresca, molho grande.',
    imagem_principal: '/placeholder.svg',
    imagens_secundarias: [],
    disponivel: true,
    destaque: false,
    status: 'ativo',
    vendedor_id: 'v1',
    provincia: 'Luanda',
    municipio: 'Viana',
    criado_em: '2026-03-02',
    atualizado_em: '2026-03-02',
    tipo_venda: 'retalho',
    quantidade_minima: 1,
  },
  {
    id: 'p3',
    nome_produto: 'Frango de Campo (Inteiro)',
    categoria: 'pecuaria',
    subcategoria: 'Aves',
    preco_aproximado: 5000,
    unidade: 'unidade',
    descricao: 'Frango de campo criado ao ar livre. Peso médio de 1.5kg a 2kg.',
    imagem_principal: '/placeholder.svg',
    imagens_secundarias: ['/placeholder.svg'],
    disponivel: true,
    destaque: true,
    status: 'ativo',
    vendedor_id: 'v2',
    provincia: 'Luanda',
    municipio: 'Cacuaco',
    criado_em: '2026-02-15',
    atualizado_em: '2026-03-01',
    tipo_venda: 'ambos',
    quantidade_minima: 1,
    preco_grosso: 3800,
    quantidade_minima_grosso: 20,
  },
  {
    id: 'p4',
    nome_produto: 'Ovos de Galinha (Bandeja 30)',
    categoria: 'pecuaria',
    subcategoria: 'Aves',
    preco_aproximado: 3500,
    unidade: 'caixa',
    descricao: 'Bandeja com 30 ovos frescos de galinha caipira.',
    imagem_principal: '/placeholder.svg',
    imagens_secundarias: [],
    disponivel: true,
    destaque: false,
    status: 'ativo',
    vendedor_id: 'v2',
    provincia: 'Luanda',
    municipio: 'Cacuaco',
    criado_em: '2026-02-20',
    atualizado_em: '2026-03-05',
    tipo_venda: 'ambos',
    quantidade_minima: 1,
    preco_grosso: 2800,
    quantidade_minima_grosso: 10,
  },
  {
    id: 'p5',
    nome_produto: 'Milho em Grão (Saco 50kg)',
    categoria: 'graos',
    subcategoria: 'Milho',
    preco_aproximado: 12000,
    unidade: 'saco',
    descricao: 'Milho em grão seco, safra 2025. Ideal para fuba e ração animal.',
    imagem_principal: '/placeholder.svg',
    imagens_secundarias: ['/placeholder.svg'],
    disponivel: true,
    destaque: true,
    status: 'ativo',
    vendedor_id: 'v3',
    provincia: 'Huambo',
    municipio: 'Huambo',
    criado_em: '2026-03-01',
    atualizado_em: '2026-03-01',
    tipo_venda: 'grosso',
    quantidade_minima: 50,
  },
  {
    id: 'p6',
    nome_produto: 'Feijão Catarino (Saco 25kg)',
    categoria: 'graos',
    subcategoria: 'Feijão',
    preco_aproximado: 8500,
    unidade: 'saco',
    descricao: 'Feijão catarino de primeira qualidade. Sem impurezas.',
    imagem_principal: '/placeholder.svg',
    imagens_secundarias: [],
    disponivel: true,
    destaque: false,
    status: 'ativo',
    vendedor_id: 'v3',
    provincia: 'Huambo',
    municipio: 'Huambo',
    criado_em: '2026-03-03',
    atualizado_em: '2026-03-03',
    tipo_venda: 'grosso',
    quantidade_minima: 25,
  },
  {
    id: 'p7',
    nome_produto: 'Sumo de Manga Natural (1L)',
    categoria: 'bebidas',
    subcategoria: 'Sumos',
    preco_aproximado: 1200,
    unidade: 'litro',
    descricao: 'Sumo de manga 100% natural, sem conservantes nem açúcar adicionado.',
    imagem_principal: '/placeholder.svg',
    imagens_secundarias: ['/placeholder.svg'],
    disponivel: true,
    destaque: true,
    status: 'ativo',
    vendedor_id: 'v4',
    provincia: 'Luanda',
    municipio: 'Belas',
    criado_em: '2026-02-10',
    atualizado_em: '2026-03-01',
    tipo_venda: 'retalho',
    quantidade_minima: 1,
  },
  {
    id: 'p8',
    nome_produto: 'Óleo de Palma (20L)',
    categoria: 'alimentos',
    subcategoria: 'Óleos',
    preco_aproximado: 15000,
    unidade: 'unidade',
    descricao: 'Óleo de palma vermelho artesanal. Bidão de 20 litros.',
    imagem_principal: '/placeholder.svg',
    imagens_secundarias: [],
    disponivel: true,
    destaque: true,
    status: 'ativo',
    vendedor_id: 'v5',
    provincia: 'Huila',
    municipio: 'Lubango',
    criado_em: '2026-02-25',
    atualizado_em: '2026-03-05',
    tipo_venda: 'grosso',
    quantidade_minima: 5,
  },
  {
    id: 'p9',
    nome_produto: 'Arroz Carolino (Saco 25kg)',
    categoria: 'grosso',
    subcategoria: 'Cereais',
    preco_aproximado: 11000,
    unidade: 'saco',
    descricao: 'Arroz carolino importado de qualidade premium. Venda por grosso.',
    imagem_principal: '/placeholder.svg',
    imagens_secundarias: [],
    disponivel: true,
    destaque: false,
    status: 'ativo',
    vendedor_id: 'v5',
    provincia: 'Huila',
    municipio: 'Lubango',
    criado_em: '2026-03-01',
    atualizado_em: '2026-03-01',
    tipo_venda: 'grosso',
    quantidade_minima: 10,
  },
  {
    id: 'p10',
    nome_produto: 'Pimenta Jindungo Fresca',
    categoria: 'frescos',
    subcategoria: 'Temperos',
    preco_aproximado: 800,
    unidade: 'kg',
    descricao: 'Jindungo fresco, bem picante. Colhido na semana.',
    imagem_principal: '/placeholder.svg',
    imagens_secundarias: [],
    disponivel: true,
    destaque: false,
    status: 'ativo',
    vendedor_id: 'v1',
    provincia: 'Luanda',
    municipio: 'Viana',
    criado_em: '2026-03-05',
    atualizado_em: '2026-03-05',
    tipo_venda: 'retalho',
    quantidade_minima: 0.5,
  },
];

export function obterVendedorPorId(id: string): Vendedor | undefined {
  return VENDEDORES_MOCK.find(v => v.id === id);
}

export function obterProdutosDoVendedor(vendedorId: string): Produto[] {
  return PRODUTOS_MOCK.filter(p => p.vendedor_id === vendedorId);
}

export function obterProdutosDestaque(): Produto[] {
  return PRODUTOS_MOCK.filter(p => p.destaque && p.disponivel);
}

export function gerarLinkWhatsApp(telefone: string, nomeProduto: string): string {
  const mensagem = encodeURIComponent(
    `Olá, vi o produto "${nomeProduto}" na ANGROLINK e gostaria de saber mais detalhes.`
  );
  return `https://wa.me/${telefone}?text=${mensagem}`;
}
