import { useEffect, useMemo, useState } from 'react';
import { useToast } from '@/hooks/use-toast';
import { criarFeedbackPiloto, type CategoriaFeedbackPiloto, type ContextoFeedbackPiloto } from '@/services/feedbackPiloto';
import { Button } from '@/components/ui/button';
import { Checkbox } from '@/components/ui/checkbox';
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from '@/components/ui/dialog';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { Textarea } from '@/components/ui/textarea';

const categorias: Array<[CategoriaFeedbackPiloto, string]> = [['aplicacao', 'Aplicação'], ['compra', 'Compra'], ['vendedor', 'Venda'], ['entrega', 'Entrega'], ['pagamento', 'Pagamento'], ['outro', 'Outro']];
export function FeedbackPilotoDialog({ aberto, aoFechar, contexto, encomendaId, atribuicaoEntregaId }: { aberto: boolean; aoFechar: () => void; contexto: ContextoFeedbackPiloto; encomendaId?: string | null; atribuicaoEntregaId?: string | null }) {
  const { toast } = useToast(); const [categoria,setCategoria]=useState<CategoriaFeedbackPiloto>('aplicacao'); const [nota,setNota]=useState(''); const [comentario,setComentario]=useState(''); const [contactar,setContactar]=useState(false); const [enviando,setEnviando]=useState(false);
  const limpar=()=>{setCategoria('aplicacao');setNota('');setComentario('');setContactar(false)};
  const categoriasVisiveis=useMemo(()=>!encomendaId?categorias.filter(([valor])=>valor==='aplicacao'||valor==='outro'):!atribuicaoEntregaId?categorias.filter(([valor])=>valor!=='entrega'):categorias,[encomendaId,atribuicaoEntregaId]);
  useEffect(()=>{if(aberto) limpar()},[aberto,contexto,encomendaId,atribuicaoEntregaId]);
  const enviar = async () => { if (enviando) return; if (!nota && !comentario.trim()) { toast({title:'Indique uma nota ou um comentário.',variant:'destructive'}); return; } try { setEnviando(true); await criarFeedbackPiloto({contexto,categoria,nota:nota ? Number(nota) : null,comentario,contactarUtilizador:contactar,encomendaId,atribuicaoEntregaId}); toast({title:'Obrigado pelo seu feedback.'}); limpar(); aoFechar(); } catch { toast({title:'Não foi possível enviar o feedback. Tenta novamente.',variant:'destructive'}); } finally { setEnviando(false); } };
  return <Dialog open={aberto} onOpenChange={valor => { if (!enviando && !valor) aoFechar(); }}><DialogContent><DialogHeader><DialogTitle>Dar feedback</DialogTitle><DialogDescription>A tua opinião ajuda-nos a melhorar o piloto.</DialogDescription></DialogHeader><div className="space-y-4"><label className="block text-sm font-medium">Categoria<Select value={categoria} onValueChange={valor => setCategoria(valor as CategoriaFeedbackPiloto)} disabled={enviando}><SelectTrigger className="mt-1"><SelectValue /></SelectTrigger><SelectContent>{categoriasVisiveis.map(([valor,rotulo])=><SelectItem key={valor} value={valor}>{rotulo}</SelectItem>)}</SelectContent></Select></label><label className="block text-sm font-medium">Nota (opcional)<select aria-label="Nota" value={nota} onChange={evento=>setNota(evento.target.value)} disabled={enviando} className="mt-1 h-10 w-full rounded-md border bg-background px-3 text-sm"><option value="">Sem nota</option>{[1,2,3,4,5].map(valor=><option key={valor} value={valor}>{valor}</option>)}</select></label><label className="block text-sm font-medium">Comentário (opcional)<Textarea value={comentario} onChange={evento=>setComentario(evento.target.value)} maxLength={1000} disabled={enviando} placeholder="Conta-nos o que correu bem ou pode melhorar." /></label><label className="flex items-center gap-2 text-sm"><Checkbox checked={contactar} onCheckedChange={valor=>setContactar(valor===true)} disabled={enviando} />Podem contactar-me sobre este feedback.</label></div><DialogFooter><Button type="button" variant="outline" disabled={enviando} onClick={aoFechar}>Cancelar</Button><Button type="button" disabled={enviando} onClick={() => void enviar()}>{enviando ? 'A enviar…' : 'Enviar feedback'}</Button></DialogFooter></DialogContent></Dialog>;
}
